#' Action codes shared with create_cleaning_log()
#'
#' The macro writes one of these into \strong{Action taken} and offers them as
#' the drop-down on the rows it appends, so they must match the codes
#' \code{create_cleaning_log()} puts on its \code{readme} and
#' \code{validation_rules} sheets.
#'
#' They are duplicated here rather than read back out of the workbook because
#' openxlsx has no \code{read.xlsx()} method for a Workbook object - only for a
#' file on disk - and the config sheet has to be added before the workbook is
#' saved. \code{test-create_cleaning_log_macro.R} asserts the two lists are
#' identical, so drift fails the test suite rather than silently producing logs
#' that \code{evaluate_cleaning_log()} rejects.
#'
#' @return Character vector of action codes.
#' @noRd
ck_action_codes <- function() {
  c(
    "recoded",
    "delete_data_point",
    "discard",
    "addition",
    "no_action",
    "other"
  )
}


#' Creates the cleaning log workbook with the change-capture macro
#'
#' A macro-enabled (\code{.xlsm}) version of \code{\link{create_cleaning_log}}.
#' The workbook is identical, plus a VBA project that watches the
#' \code{dataset} sheet: every edit a reviewer makes there is appended
#' automatically to the bottom of the cleaning log, so a change never has to be
#' copied across by hand.
#'
#' @details
#' This is a thin wrapper. It calls \code{\link{create_cleaning_log}} with
#' \code{output_path = NULL} to build the ordinary workbook, adds one
#' very-hidden configuration sheet, and injects the compiled VBA project into
#' the saved package. \code{create_cleaning_log()} itself is not modified and
#' does not know this function exists - so if anything about the macro route
#' breaks (a missing binary, a blocked macro, an Excel upgrade), the plain
#' \code{.xlsx} path is completely unaffected. Every argument below behaves
#' exactly as it does there.
#'
#' \strong{Two extra sheets.} \code{_ck_config} holds the sheet and column names
#' the macro reads, so one compiled binary serves every log the package
#' produces. \code{_ck_ledger} is created by the macro itself on the first edit
#' and remembers, per cell, the original raw value, the latest value and the
#' edit count. Both are \code{veryHidden}, so they do not appear in Excel's
#' Unhide dialog.
#'
#' \strong{What an edit produces.} A row carrying \strong{Survey UUID},
#' \strong{Date}, \strong{Enumerator}, \strong{Question number},
#' \strong{Question text}, \strong{Old value}, \strong{New value},
#' \strong{Identified by} and a mapped \strong{Action taken} - \code{addition}
#' when the cell was empty, \code{delete_data_point} when it is cleared,
#' \code{recoded} otherwise.
#'
#' \strong{Repeat edits.} Editing the same cell again appends \emph{another}
#' row rather than revising the first, so the log keeps the full history. Each
#' row's \strong{Old value} is the value immediately before that edit, so
#' successive rows chain raw -> A -> B. To keep those rows distinct through
#' \code{\link{read_cleaning_log}}, whose deduplication key is
#' \code{uuid + question + issue}, the Nth edit is written with \strong{Issue}
#' \code{"manual_edit_00N"}. The sequence numbers sort in edit order, so
#' \code{\link{apply_cleaning_log}} applies the most recent value last.
#'
#' \strong{Formatting.} Appended rows have their formatting cleared before they
#' are written and \code{Application.ExtendList} is suspended during the write,
#' so none of the \code{\link{create_formated_wb}} row colours carry down onto
#' them. They are given the same \strong{Action taken} drop-down as the rest of
#' the log.
#'
#' \strong{Protected cells.} The macro restores the header and label rows and
#' the uuid column if they are edited, because the log refers to them.
#'
#' \strong{Prerequisite.} The compiled VBA project is not generated by R. It is
#' built once from the sources in \code{inst/vba/} with
#' \code{dev/build_vba_bin.R} (or by hand - see \code{inst/vba/README.md}) and
#' found by \code{\link{ck_vba_project_path}}. If it cannot be found, this
#' function stops with a message listing every location it searched; use
#' \code{create_cleaning_log()} in the meantime.
#'
#' \strong{Reading the result back.} \code{readxl} reads \code{.xlsm} exactly
#' like \code{.xlsx}, but remember to widen \code{file_pattern} when scanning a
#' directory with \code{\link{read_cleaning_log}}.
#'
#' @inheritParams create_cleaning_log
#' @param output_path Path for the macro-enabled workbook. Required - a VBA
#'   project cannot be attached to a workbook object, so unlike
#'   \code{create_cleaning_log()} this function cannot return one. An
#'   \code{.xlsx} extension is corrected to \code{.xlsm} with a message.
#' @param macro_issue_prefix Prefix used to build the \strong{Issue} value of
#'   macro-appended rows. The Nth edit of a given cell is written as
#'   \code{"<prefix>_00N"}. Default \code{"manual_edit"}.
#' @param vba_project Path to the compiled \code{vbaProject.bin} to inject.
#'   Default \code{NULL} uses \code{\link{ck_vba_project_path}}.
#'
#' @return The output path, invisibly.
#' @export
#'
#' @seealso \code{\link{create_cleaning_log}} for the plain \code{.xlsx}
#'   version, \code{\link{add_vba_project}} for the injection step and
#'   \code{\link{ck_vba_project_path}} for how the binary is located.
#'
#' @examples
#' \dontrun{
#' create_cleaning_log_vba(
#'   write_list,
#'   output_path = "cleaning_log.xlsm"
#' )
#'
#' # point at a binary that is not on the default search path
#' create_cleaning_log_vba(
#'   write_list,
#'   output_path = "cleaning_log.xlsm",
#'   vba_project = "resources/cleaningkit_vba.bin"
#' )
#' }
create_cleaning_log_vba <- function(
  write_list,
  output_path,
  cleaning_log_name = "cleaning_log",
  dataset_name = "checked_dataset",
  uuid_column = "_uuid",
  enumerator_column = "username",
  date_column = "today",
  column_for_color = "check_binding",
  color_mode = "on",
  color_columns = NULL,
  header_front_size = 12,
  header_front_color = "#FFFFFF",
  header_fill_color = "#00A2A5",
  header_front = "Arial Narrow",
  body_front = "Arial Narrow",
  body_front_size = 11,
  skip_label_row = TRUE,
  group_by_uuid = TRUE,
  macro_issue_prefix = "manual_edit",
  vba_project = NULL
) {
  # ---- pre-flight ----
  # Everything that can fail cheaply is checked before the workbook is built,
  # because building it is the expensive part.
  if (missing(output_path) || is.null(output_path)) {
    stop(
      "`output_path` is required: a VBA project cannot be attached to a ",
      "workbook object, only to a saved file. Use create_cleaning_log() if you ",
      "want a workbook returned.",
      call. = FALSE
    )
  }
  if (is.list(write_list) && "_ck_config" %in% names(write_list)) {
    stop(
      "The list already has an element named `_ck_config`. Please rename it.",
      call. = FALSE
    )
  }

  resolved_vba <- if (is.null(vba_project)) {
    ck_vba_project_path()
  } else {
    vba_project
  }
  if (!nzchar(resolved_vba) || !file.exists(resolved_vba)) {
    if (!is.null(vba_project)) {
      stop(
        "`vba_project` does not point at a file that exists:\n  ",
        vba_project,
        call. = FALSE
      )
    }
    stop(ck_vba_missing_message(), call. = FALSE)
  }

  # ---- build the ordinary workbook, untouched ----
  # include_dataset is forced: the macro watches the `dataset` sheet, so without
  # it there is nothing for a reviewer to edit.
  workbook <- create_cleaning_log(
    write_list = write_list,
    cleaning_log_name = cleaning_log_name,
    dataset_name = dataset_name,
    uuid_column = uuid_column,
    enumerator_column = enumerator_column,
    date_column = date_column,
    column_for_color = column_for_color,
    color_mode = color_mode,
    color_columns = color_columns,
    include_dataset = TRUE,
    header_front_size = header_front_size,
    header_front_color = header_front_color,
    header_fill_color = header_fill_color,
    header_front = header_front,
    body_front = body_front,
    body_front_size = body_front_size,
    skip_label_row = skip_label_row,
    output_path = NULL,
    group_by_uuid = group_by_uuid
  )

  if (!("dataset" %in% names(workbook))) {
    stop(
      "The workbook has no `dataset` sheet, so there is nothing for the macro ",
      "to watch.",
      call. = FALSE
    )
  }

  # ---- the macro's configuration sheet ----
  # Row layout of the dataset sheet as written: openxlsx puts the column names
  # on row 1, so the ONA label row lands on row 2 and the records start on
  # row 3. Without a label row everything shifts up by one.
  config <- ck_macro_config_df(
    dataset_sheet = "dataset",
    log_sheet = cleaning_log_name,
    uuid_column = uuid_column,
    date_column = date_column,
    enumerator_column = enumerator_column,
    issue_prefix = macro_issue_prefix,
    action_codes = ck_action_codes(),
    body_front = body_front,
    body_front_size = body_front_size,
    header_row = 1L,
    label_row = if (isTRUE(skip_label_row)) 2L else 0L,
    first_data_row = if (isTRUE(skip_label_row)) 3L else 2L
  )

  # Added last so the positions of the existing sheets do not move, and
  # veryHidden so it stays out of Excel's Unhide dialog.
  openxlsx::addWorksheet(workbook, "_ck_config", visible = "veryHidden")
  openxlsx::writeData(workbook, sheet = "_ck_config", config, rowNames = FALSE)

  # ---- save and inject ----
  if (!grepl("\\.xlsm$", output_path, ignore.case = TRUE)) {
    output_path <- paste0(
      sub("\\.xlsx$", "", output_path, ignore.case = TRUE),
      ".xlsm"
    )
    message(
      "create_cleaning_log_vba: a macro-enabled workbook must be .xlsm; ",
      "output_path changed to '",
      output_path,
      "'."
    )
  }

  tmp_xlsx <- tempfile("ck_log_", fileext = ".xlsx")
  on.exit(unlink(tmp_xlsx, force = TRUE), add = TRUE)
  openxlsx::saveWorkbook(workbook, tmp_xlsx, overwrite = TRUE)

  add_vba_project(
    xlsx_path = tmp_xlsx,
    xlsm_path = output_path,
    vba_project = resolved_vba,
    overwrite = TRUE
  )

  invisible(output_path)
}
