#' Set Up Project Folder Structure
#'
#' Creates the standard folder structure used by the data cleaning pipeline.
#' Safe to run on an existing project — folders that already exist are skipped
#' with an informational message rather than overwritten or errored.
#'
#' @details
#' The following folders are created (relative to \code{base_path}):
#' \describe{
#'   \item{\code{data/}}{Raw data exports from ONA or other XLSForm platforms.}
#'   \item{\code{resources/}}{Supporting files: XLSForm tool, kobo/ONA choices,
#'     label files, logical check lists, etc.}
#'   \item{\code{output/}}{All outputs generated by the pipeline.}
#'   \item{\code{output/other_responses/}}{Filled other-responses review files
#'     matching the pattern \code{_other_responses_edited.xlsx}.}
#'   \item{\code{output/follow_ups/}}{Filled cleaning log review files matching
#'     the pattern \code{_follow-ups_edited.xlsx}.}
#'   \item{\code{output/final/}}{Final output workbooks produced by
#'     \code{export_final_output()}.}
#' }
#'
#' @param base_path Root directory of the project. Default \code{"."} (current
#'   working directory). Use \code{here::here()} for reproducible paths inside
#'   an R project.
#' @param extra_folders Optional character vector of additional folder paths to
#'   create relative to \code{base_path} (e.g. \code{c("output/archive",
#'   "output/checking")}). Default \code{NULL}.
#' @param verbose Logical. If \code{TRUE} (the default), a message is printed
#'   for each folder showing whether it was created or already existed.
#'
#' @return Invisibly returns a named logical vector: \code{TRUE} for each folder
#'   that was newly created, \code{FALSE} for folders that already existed.
#' @export
setup_project_folders <- function(
  base_path = ".",
  extra_folders = NULL,
  verbose = TRUE
) {
  # ---- standard folders ----
  standard_folders <- c(
    "data",
    "resources",
    "output",
    "output/other_responses",
    "output/follow_ups",
    "output/final"
  )

  all_folders <- c(standard_folders, extra_folders)

  # ---- resolve full paths ----
  full_paths <- file.path(base_path, all_folders)
  names(full_paths) <- all_folders

  # ---- create each folder ----
  results <- vapply(
    all_folders,
    function(folder) {
      full <- file.path(base_path, folder)
      if (dir.exists(full)) {
        if (verbose) {
          message("  \u2713 already exists: ", folder)
        }
        return(FALSE)
      }
      dir.create(full, recursive = TRUE, showWarnings = FALSE)
      if (dir.exists(full)) {
        if (verbose) {
          message("  \u2714 created:         ", folder)
        }
        return(TRUE)
      } else {
        warning(paste0("Could not create folder: ", full))
        return(FALSE)
      }
    },
    logical(1)
  )

  # ---- summary ----
  n_created <- sum(results)
  n_existing <- sum(!results)
  if (verbose) {
    message(
      "\nsetup_project_folders: ",
      n_created,
      " folder(s) created, ",
      n_existing,
      " already existed",
      if (!is.null(base_path) && base_path != ".") {
        paste0(" (base: ", base_path, ")")
      } else {
        ""
      }
    )
  }

  invisible(results)
}
